import styled from 'styled-components';

export const Container = styled.div`
  display: flex;
  justify-content: center;

  width: 100%;

  @keyframes ldio-sn01i1tu5f {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }

  .ldio-sn01i1tu5f div {
    position: absolute;
    width: 48px;
    height: 48px;
    border: 12px solid #626767;
    border-top-color: transparent;
    border-radius: 50%;
  }

  .ldio-sn01i1tu5f div {
    animation: ldio-sn01i1tu5f 1s linear infinite;
    top: 100px;
    left: 100px;
  }

  .loadingio-spinner-rolling-jx5vlp48qe {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: transparent;
  }
  .ldio-sn01i1tu5f {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-sn01i1tu5f div {
    box-sizing: content-box;
  }

  /* generated by https://loading.io */
`;
